### ISSUE TITLE
Play local video with full file path

### ISSUE THREAD

**Issue by seansong327** [hardikdevios/cordova-plugin-hkvideoplayer#1]
First I want to say good job man.

But what I'm trying to do now is play a video with full path rather than in folder "www/assets/video".

Video path example "file:///private/var/mobile/Containers/Data/Application/DD2A20D3-F15D-4CB8-9287-DADCAEB1D86E/tmp/trim.9D107592-71A8-411F-B159-E5CB6016444F.MOV"

I know nothing about swift, just want to kown is this possible?

**Comment by hardikdevios** [comment]
@seansong327 can you try this 

HKVideoPlayer.play("Your path here");

Let me know if it works for you.

**Comment by seansong327** [comment]
@hardikdevios Yes, it works.  
Sorry I should try first, I thought it can only play videoes form network or asserts.

A big thanks to you, this package helps me a lot.
